import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";

// ─── helpers ────────────────────────────────────────────────────────────────
const pk = () =>
  text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID());
const createdAt = () =>
  text("created_at")
    .notNull()
    .$defaultFn(() => new Date().toISOString());

// ─── shops ──────────────────────────────────────────────────────────────────
export const shops = sqliteTable("shops", {
  id: pk(),
  name: text("name").notNull(),
  ownerName: text("owner_name"),
  address: text("address"),
  email: text("email"),
  ownerWhatsapp: text("owner_whatsapp"),
  ownerPinHash: text("owner_pin_hash").notNull(),
  cashierPinHash: text("cashier_pin_hash").notNull(),
  geminiApiKey: text("gemini_api_key"),
  groqApiKey: text("groq_api_key"),
  createdAt: createdAt(),
});

export type Shop = typeof shops.$inferSelect;
export type InsertShop = typeof shops.$inferInsert;

// ─── products ───────────────────────────────────────────────────────────────
export const products = sqliteTable("products", {
  id: pk(),
  shopId: text("shop_id")
    .notNull()
    .references(() => shops.id),
  canonicalName: text("canonical_name").notNull(),
  normalizedName: text("normalized_name").notNull(),
  sku: text("sku"),
  category: text("category"),
  unit: text("unit").notNull().default("unit"),
  purchasePrice: real("purchase_price"),
  sellingPrice: real("selling_price"),
  profitMargin: real("profit_margin"),
  productType: text("product_type").notNull().default("normal"),
  allowDecimals: integer("allow_decimals", { mode: "boolean" }).notNull().default(false),
  stockQty: real("stock_qty").notNull().default(0),
  alertQty: real("alert_qty").notNull().default(5),
  expiryDate: text("expiry_date"),
  tokensJson: text("tokens_json"),
  size: text("size"),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  lastSoldAt: text("last_sold_at"),
  createdAt: createdAt(),
  updatedAt: text("updated_at")
    .notNull()
    .$defaultFn(() => new Date().toISOString()),
});

export type Product = typeof products.$inferSelect;
export type InsertProduct = typeof products.$inferInsert;

// ─── product aliases ─────────────────────────────────────────────────────────
export const productAliases = sqliteTable("product_aliases", {
  id: pk(),
  productId: text("product_id")
    .notNull()
    .references(() => products.id, { onDelete: "cascade" }),
  alias: text("alias").notNull(),
  confidence: real("confidence"),
  autoGenerated: integer("auto_generated", { mode: "boolean" })
    .notNull()
    .default(false),
  createdAt: createdAt(),
});

export type ProductAlias = typeof productAliases.$inferSelect;
export type InsertProductAlias = typeof productAliases.$inferInsert;

// ─── price history ───────────────────────────────────────────────────────────
export const priceHistory = sqliteTable("price_history", {
  id: pk(),
  productId: text("product_id")
    .notNull()
    .references(() => products.id, { onDelete: "cascade" }),
  oldPurchasePrice: real("old_purchase_price"),
  newPurchasePrice: real("new_purchase_price"),
  oldSellingPrice: real("old_selling_price"),
  newSellingPrice: real("new_selling_price"),
  pctChange: real("pct_change"),
  changedBy: text("changed_by"),
  changedAt: text("changed_at")
    .notNull()
    .$defaultFn(() => new Date().toISOString()),
});

export type PriceHistoryRow = typeof priceHistory.$inferSelect;
export type InsertPriceHistory = typeof priceHistory.$inferInsert;

// ─── sales ───────────────────────────────────────────────────────────────────
export const sales = sqliteTable("sales", {
  id: pk(),
  shopId: text("shop_id")
    .notNull()
    .references(() => shops.id),
  totalAmount: real("total_amount").notNull().default(0),
  totalCost: real("total_cost"),
  totalProfit: real("total_profit"),
  discount: real("discount").notNull().default(0),
  saleType: text("sale_type", { enum: ["cash", "debt"] })
    .notNull()
    .default("cash"),
  servedBy: text("served_by"),
  syncStatus: text("sync_status").notNull().default("synced"),
  isDeleted: integer("is_deleted", { mode: "boolean" }).notNull().default(false),
  deletedAt: text("deleted_at"),
  deleteReason: text("delete_reason"),
  deletedBy: text("deleted_by"),
  createdAt: createdAt(),
});

export type Sale = typeof sales.$inferSelect;
export type InsertSale = typeof sales.$inferInsert;

// ─── sale items ──────────────────────────────────────────────────────────────
export const saleItems = sqliteTable("sale_items", {
  id: pk(),
  saleId: text("sale_id")
    .notNull()
    .references(() => sales.id, { onDelete: "cascade" }),
  productId: text("product_id"),
  productName: text("product_name").notNull(),
  qty: real("qty").notNull(),
  unitPrice: real("unit_price").notNull(),
  unitCost: real("unit_cost"),
  unitProfit: real("unit_profit"),
  totalPrice: real("total_price").notNull(),
  totalProfit: real("total_profit"),
});

export type SaleItem = typeof saleItems.$inferSelect;
export type InsertSaleItem = typeof saleItems.$inferInsert;

// ─── debts ───────────────────────────────────────────────────────────────────
export const debts = sqliteTable("debts", {
  id: pk(),
  shopId: text("shop_id")
    .notNull()
    .references(() => shops.id),
  saleId: text("sale_id"),
  customerName: text("customer_name").notNull(),
  customerPhone: text("customer_phone").notNull().default(""),
  totalAmount: real("total_amount").notNull(),
  amountPaid: real("amount_paid").notNull().default(0),
  balance: real("balance").notNull(),
  status: text("status", { enum: ["unpaid", "partial", "paid"] })
    .notNull()
    .default("unpaid"),
  notes: text("notes"),
  paidAt: text("paid_at"),
  createdAt: createdAt(),
});

export type Debt = typeof debts.$inferSelect;
export type InsertDebt = typeof debts.$inferInsert;

// ─── debt payments ───────────────────────────────────────────────────────────
export const debtPayments = sqliteTable("debt_payments", {
  id: pk(),
  debtId: text("debt_id")
    .notNull()
    .references(() => debts.id, { onDelete: "cascade" }),
  amount: real("amount").notNull(),
  recordedBy: text("recorded_by"),
  paidAt: text("paid_at").notNull().$defaultFn(() => new Date().toISOString()),
});

export type DebtPayment = typeof debtPayments.$inferSelect;
export type InsertDebtPayment = typeof debtPayments.$inferInsert;

// ─── inventory movements ─────────────────────────────────────────────────────
export const inventoryMovements = sqliteTable("inventory_movements", {
  id: pk(),
  productId: text("product_id")
    .notNull()
    .references(() => products.id),
  productName: text("product_name"),
  movementType: text("movement_type").notNull(),
  qtyChange: real("qty_change").notNull(),
  beforeQty: real("before_qty").notNull(),
  afterQty: real("after_qty").notNull(),
  source: text("source"),
  referenceId: text("reference_id"),
  createdBy: text("created_by"),
  createdAt: createdAt(),
});

export type InventoryMovement = typeof inventoryMovements.$inferSelect;
export type InsertInventoryMovement = typeof inventoryMovements.$inferInsert;

// ─── notifications ───────────────────────────────────────────────────────────
export const notifications = sqliteTable("notifications", {
  id: pk(),
  shopId: text("shop_id")
    .notNull()
    .references(() => shops.id),
  type: text("type").notNull(),
  title: text("title").notNull(),
  message: text("message").notNull(),
  productId: text("product_id"),
  debtId: text("debt_id"),
  isRead: integer("is_read", { mode: "boolean" }).notNull().default(false),
  createdAt: createdAt(),
});

export type Notification = typeof notifications.$inferSelect;
export type InsertNotification = typeof notifications.$inferInsert;

// ─── audit log ───────────────────────────────────────────────────────────────
export const auditLog = sqliteTable("audit_log", {
  id: pk(),
  shopId: text("shop_id").notNull(),
  action: text("action").notNull(),
  entityType: text("entity_type"),
  entityId: text("entity_id"),
  oldValueJson: text("old_value_json"),
  newValueJson: text("new_value_json"),
  performedBy: text("performed_by"),
  createdAt: createdAt(),
});

export type AuditEntry = typeof auditLog.$inferSelect;
export type InsertAuditEntry = typeof auditLog.$inferInsert;

// ─── suppliers ───────────────────────────────────────────────────────────────
export const suppliers = sqliteTable("suppliers", {
  id: pk(),
  shopId: text("shop_id")
    .notNull()
    .references(() => shops.id),
  name: text("name").notNull(),
  phone: text("phone"),
  notes: text("notes"),
  createdAt: createdAt(),
});

export type Supplier = typeof suppliers.$inferSelect;
export type InsertSupplier = typeof suppliers.$inferInsert;

// ─── stock transfers ─────────────────────────────────────────────────────────
export const stockTransfers = sqliteTable("stock_transfers", {
  id: pk(),
  fromShopId: text("from_shop_id").notNull(),
  toShopId: text("to_shop_id").notNull(),
  fromProductId: text("from_product_id").notNull(),
  toProductId: text("to_product_id").notNull(),
  productName: text("product_name").notNull(),
  qty: real("qty").notNull(),
  unit: text("unit"),
  notes: text("notes"),
  transferredBy: text("transferred_by"),
  createdAt: createdAt(),
});

export type StockTransfer = typeof stockTransfers.$inferSelect;
export type InsertStockTransfer = typeof stockTransfers.$inferInsert;

// ─── sale returns ────────────────────────────────────────────────────────────
export const saleReturns = sqliteTable("sale_returns", {
  id: pk(),
  shopId: text("shop_id")
    .notNull()
    .references(() => shops.id),
  saleId: text("sale_id")
    .notNull()
    .references(() => sales.id),
  itemsJson: text("items_json").notNull(),
  totalRefund: real("total_refund").notNull(),
  reason: text("reason"),
  processedBy: text("processed_by"),
  createdAt: createdAt(),
});

export type SaleReturn = typeof saleReturns.$inferSelect;
export type InsertSaleReturn = typeof saleReturns.$inferInsert;

// ─── quotations ──────────────────────────────────────────────────────────────
export const quotations = sqliteTable("quotations", {
  id: pk(),
  shopId: text("shop_id").notNull().references(() => shops.id),
  quoteNumber: text("quote_number").notNull(),
  customerName: text("customer_name").notNull(),
  customerPhone: text("customer_phone").notNull().default(""),
  customerEmail: text("customer_email"),
  status: text("status", { enum: ["draft", "sent", "accepted", "rejected", "expired"] })
    .notNull()
    .default("draft"),
  notes: text("notes"),
  validUntil: text("valid_until"),
  subtotal: real("subtotal").notNull().default(0),
  discountAmount: real("discount_amount").notNull().default(0),
  total: real("total").notNull().default(0),
  itemsJson: text("items_json").notNull().default("[]"),
  createdBy: text("created_by"),
  createdAt: createdAt(),
});

export type Quotation = typeof quotations.$inferSelect;
export type InsertQuotation = typeof quotations.$inferInsert;

// ─── scan sessions ───────────────────────────────────────────────────────────
export const scanSessions = sqliteTable("scan_sessions", {
  id: pk(),
  shopId: text("shop_id")
    .notNull()
    .references(() => shops.id),
  scanType: text("scan_type", { enum: ["notebook", "invoice"] }).notNull(),
  totalImages: integer("total_images").notNull().default(0),
  totalProducts: integer("total_products").notNull().default(0),
  status: text("status").notNull().default("pending"),
  resultJson: text("result_json"),
  createdAt: createdAt(),
});

export type ScanSession = typeof scanSessions.$inferSelect;
export type InsertScanSession = typeof scanSessions.$inferInsert;
